# Beast academy has 5 levels, within that are x chapters, within that are y lessons, within that are z questions
# These values are stuffed into this file -> https://beastacademy.com/dist/v9.77.3/bundle_core.js
ba_level_chapters_map = {
    # level one has 12 chapters
    'level_one': [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
    'level_two': [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75],
    'level_three': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    'level_four': [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
    'level_five': [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
}

all_chapter_ids = {
    # level 1
    '78': 'Counting',
    '79': 'Shapes',
    '80': 'Comparing',
    '81': 'Addition',
    '82': 'Subtraction',
    '83': 'Categories',
    '84': 'Addition & Subtraction',
    '85': 'Comparing',
    '86': 'Patterns',
    '87': 'Big Numbers',
    '88': 'Measurement',
    '89': 'Problem Solving',
    # level 2
    '64': 'Place Value',
    '65': 'Comparing',
    '66': 'Addition',
    '67': 'Subtraction',
    '68': 'Expressions',
    '69': 'Problem Solving',
    '70': 'Measurement',
    '71': 'Strategies (+ & -)',
    '72': 'Odds & Evens',
    '73': 'Big Numbers',
    '74': 'Algorithms (+ & -)',
    '75': 'Problem Solving',
    # level 3
    '1': 'Shapes',
    '2': 'Skip-Counting',
    '3': 'Perimeter & Area',
    '4': 'Multiplication',
    '5': 'Perfect Squares',
    '6': 'The Distributive Property',
    '7': 'Variables',
    '8': 'Division',
    '9': 'Measurement',
    '10': 'Fractions',
    '11': 'Estimation',
    '12': 'Area',
    # level 4
    '14': 'Shapes',
    '15': 'Multiplication',
    '16': 'Exponents',
    '17': 'Counting',
    '18': 'Division',
    '19': 'Logic',
    '20': 'Factors',
    '21': 'Fractions (+ & -)',
    '22': 'Integers',
    '23': 'Fractions (Ã— & Ã·)',
    '24': 'Decimals',
    '25': 'Probability',
    # level 5
    '52': '3D Solids',
    '53': 'Integers',
    '54': 'Expressions & Equations',
    '55': 'Statistics',
    '56': 'Factors & Multiples',
    '57': 'Fractions',
    '58': 'Sequences',
    '59': 'Ratios & Rates',
    '60': 'Decimals',
    '61': 'Percents',
    '62': 'Square Roots',
    '63': 'Exponents'
}

all_chapter_names = {
    # level 1
    'Counting': '78',
    'Shapes': '79',
    'Comparing': '80',
    'Addition': '81',
    'Subtraction': '82',
    'Categories': '83',
    'Addition & Subtraction': '84',
    'Comparing': '85',
    'Patterns': '86',
    'Big Numbers': '87',
    'Measurement': '88',
    'Problem Solving': '89',
    # level 2
    'Place Value': '64',
    'Comparing': '65',
    'Addition': '66',
    'Subtraction': '67',
    'Expressions': '68',
    'Problem Solving': '69',
    'Measurement': '70',
    'Strategies (+ & -)': '71',
    'Odds & Evens': '72',
    'Big Numbers': '73',
    'Algorithms (+ & -)': '74',
    'Problem Solving': '75',
    # level 3
    'Shapes': '1',
    'Skip-Counting': '2',
    'Perimeter & Area': '3',
    'Multiplication': '4',
    'Perfect Squares': '5',
    'The Distributive Property': '6',
    'Variables': '7',
    'Division': '8',
    'Measurement': '9',
    'Fractions': '10',
    'Estimation': '11',
    'Area': '12',
    # level 4
    'Shapes': '14',
    'Multiplication': '15',
    'Exponents': '16',
    'Counting': '17',
    'Division': '18',
    'Logic': '19',
    'Factors': '20',
    'Fractions (+ & -)': '21',
    'Integers': '22',
    'Fractions (Ã— & Ã·)': '23',
    'Decimals': '24',
    'Probability': '25',
    # level 5
    '3D Solids': '52',
    'Integers': '53',
    'Expressions & Equations': '54',
    'Statistics': '55',
    'Factors & Multiples': '56',
    'Fractions': '57',
    'Sequences': '58',
    'Ratios & Rates': '59',
    'Decimals': '60',
    'Percents': '61',
    'Square Roots': '62',
    'Exponents': '63'
}
